### PR TITLE
2014 General Election Precinct-level Results

### PR DESCRIPTION
**Pull request by charles-difazio**
Parsed from the California Redistricting Committee Statewide Database.

### CODE REVIEW

**Comment by charles-difazio** [comment]
I can break this into individual county-level commits if that'd be preferable.

Preparing the parsing code for checkin in a followup commit.

**Comment by dwillis** [comment]
That would be awesome if you could, thanks!

**Comment by charles-difazio** [comment]
Done splitting these out to one commit per county.  Rather than generating a pull request per commit, I've left them still in a single branch so you don't have to approve 58 pull requests.

**Comment by dwillis** [comment]
Thanks!

**Comment by dwillis** [comment]
@charles-difazio I think I screwed up the merging process - what branch are the single-county files on?

**Comment by charles-difazio** [comment]
I'm not a Github expert, but it looked to me like the merging process went right.

The description for your merge commit (3a1966c) was the pull request title, but the history still contained the separate per-county commits.  Looking at the directory at the merge commit ([link](https://github.com/openelections/openelections-data-ca/tree/3a1966c8efe0b9e282dcb46e4c32090831eaa50b/2014)), the commit messages for each county's files are appropriate, and the history for the directory ([link](https://github.com/openelections/openelections-data-ca/commits/3a1966c8efe0b9e282dcb46e4c32090831eaa50b/2014?page=1)) contains a commit-per-county.

Sorry for the response lag, I'm on California time and can only work on this in my spare time.

**Comment by dwillis** [comment]
No worries, I'll figure it out :-)

**Pull request merged**
