### PR TITLE
Remove leading and trailing whitespace

### PR DESCRIPTION
**Pull request by warwickmm**
This removes unnecessary leading and trailing whitespace from the data entries.

### CODE REVIEW

**Comment by warwickmm** [comment]
Some of these same files also suffer from multiple consecutive whitespaces.  I plan to address that issue in a separate pull request.

**Comment by warwickmm** [comment]
I realized that the number of changes made here is unwieldy.  @dwillis, would it help to break this pull request up into smaller pieces?

**Comment by dwillis** [comment]
@warwickmm no, i think it's fine. i just hadn't gotten to look at this until this evening.

**Comment by warwickmm** [comment]
No worries, I didn't mean to rush anything.  I just wanted to make the review process as simple as possible, especially when so many lines are touched.

**Pull request merged**
