### PR TITLE
adding Alameda general

### PR DESCRIPTION
**Pull request by aidanconnolly**
Per #144, this includes a preliminary version of the Alameda county results. I have a couple questions:

The results did not include party information, so I pulled it from [https://www.acgov.org/rov_app/candidatelist](https://www.acgov.org/rov_app/candidatelist). Would you prefer I don't do that and we just use the information provided?

The [example provided of Marin County](https://github.com/openelections/openelections-data-ca/blob/master/2020/20201103__ca__general__marin__precinct.csv) didn't have under/over votes, so I wasn't sure how to handle that data, but I see them in [the Calaveras County results](https://github.com/openelections/openelections-data-ca/blob/master/2020/20201103__ca__general__calaveras__precinct.csv). Would you prefer those be included in this sheet?

The Calaveras County sheet doesn't include county totals for registered voters and ballots cast, but the Marin County sheet does. I went ahead and calculated them for Alameda County, but should I leave that out?

I filtered out races that weren't a part of U.S. Senate, U.S. House, or state legislative races, but the Marin County sheet has other races. Should I put those back in?

Let me know if there's anything else in the Alameda sheet that should be changed, and then I'll apply this process to the other counties. Thanks!

### CODE REVIEW

**Comment by dwillis** [comment]
@aidanconnolly thanks! to your questions:

1. You may add party information, absolutely - that definitely helps us.
2. Over and Under Votes should be treated like candidate results; Calaveras County is a good example.
3. If the county doesn't include registered voters and ballots cast figures don't calculate them; just do the candidate results.
4. The counties that have races other than the ones we want, like Marin, usually happen when they provide a spreadsheet as opposed to a PDF. It's up to you - we'll happily accept more races - but the ones listed in the original issue are the only ones we require.

**Comment by aidanconnolly** [comment]
@dwillis Great! Sorry for the delay on incorporating your suggestions, but those are now in. I added the other races beyond the national and state legislative races, but I didn't go through the effort to add party information to those candidates. Let me know if this is an issue.

**Comment by dwillis** [comment]
@aidanconnolly thanks! one minor thing: the filename should be all lowercase.

**Comment by aidanconnolly** [comment]
@dwillis Got it. Should be fixed now!

**Pull request merged**
