### PR TITLE
Add Tulare General 2020

### PR DESCRIPTION
**Pull request by goodasha**

### CODE REVIEW

**Comment by dwillis** [comment]
@goodasha thanks - can you change the filename to reflect that this is for the general election, so `20201103__ca__general__tulare__precinct.csv`? Many thanks!

**Comment by goodasha** [comment]
Before I correct _that_ mistake - question: I believe I should also include the Precinct Turnout report - which I missed. 
If that is the case, can you confirm the columns? PDF has by precinct: registered, votes, election_day and mail. For a precinct, would there be rows for:

- candidate=registered
- candidate=votes, with add'l columns for election_day and mail counts

Or just simply four rows per precinct, with registered, votes, election_day, and mail reported separately?

**Comment by dwillis** [comment]
@goodasha yes, thank you. Your first solution is the right one, with one change: put "Registered Voters" in `office`, not `candidate` and do the same for `Ballots Cast`.

**Comment by dwillis** [comment]
@goodasha just one more thing - it's 20201103, not 20200303 in the filename.

**Pull request merged**
